# Generated by Django 2.1.7 on 2019-02-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='ticket_class',
            new_name='pclass',
        ),
    ]
